Added error() function.

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -1,5 +1,18 @@
 #!/bin/bash 
 
+function error(){
+  ## Error handling trap
+  # Displays line number where error occurred and prints exit status of last command
+  # Exits with said status.
+  local PARENT_LINENO="$1" ; local MESSAGE="$2" ; local CODE="${3:-1}"
+  if [[ -n "$MESSAGE" ]] ; then
+    echo "Error on or near line ${PARENT_LINENO}: ${MESSAGE}; exiting with status ${CODE}"
+  else
+    echo "Error on or near line ${PARENT_LINENO}; exiting with status ${CODE}"
+  fi
+  exit "${CODE}"
+}
+
 function ipprint(){ 
   ## Prints in "hostname:	###.###.###.###" format the string of hosts or file hosts (newline delimited) passed.
   LST=$@   
